version: '3.8'
services:
  gateway:
    build: ./gateway
    image: gateway-dock
    container_name: gateway_container
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - server.port=8080

  server:
    build: ./server
    image: server-dock
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareitDB
      - server.port=9090

  db:
    image: postgres:13.7-alpine
    container_name: postgres_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareitDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres